version: 1
from: "infracamp/kickstart-flavor-arm32v7-php7:testing"
apache_fallback_resource: "/index.php"

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"
    - "sudo apt-get install -y wpasupplicant iw wireless-tools iproute2 netscript chromium-browser"
    - 'echo "www-data   ALL = (ALL) NOPASSWD:   ALL" | sudo tee -a /etc/sudoers > /dev/null'

  run:
    - "xhost +"

  dev:
    - "xhost +"
